/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query Page($slug: String!, $locale: I18NLocaleCode) {\n    pages(filters: { slug: { eq: $slug } }, locale: $locale) {\n      title\n      sections {\n        __typename\n        ... on ComponentSectionsHero {\n          heading\n          introduction\n          subheading\n        }\n        ... on ComponentSectionsFeaturedStages {\n          heading\n        }\n        ... on ComponentSectionsExploreCta {\n          heading\n        }\n      }\n      seo {\n        metaDescription\n        metaTitle\n        ogImage {\n          alternativeText\n          url\n          caption\n        }\n      }\n    }\n  }\n": typeof types.PageDocument,
    "\n  query Prefectures {\n    prefectures {\n      nameJa\n      nameEn\n      code\n      region\n    }\n  }\n": typeof types.PrefecturesDocument,
    "\n  query Stages(\n    $locale: I18NLocaleCode\n    $sort: [String]\n    $page: Int\n    $pageSize: Int\n    $filters: StageFiltersInput\n  ) {\n    stages_connection(\n      locale: $locale\n      sort: $sort\n      pagination: { page: $page, pageSize: $pageSize }\n      filters: $filters\n    ) {\n      nodes {\n        documentId\n        slug\n        stageNumber\n        date\n        title\n        excerpt\n        startNameEn\n        endNameEn\n        startNameJa\n        endNameJa\n        featured\n        routePreview\n        stats {\n          distanceKm\n          elevationGainM\n          movingTimeMin\n        }\n        coverImage {\n          url\n          alternativeText\n          width\n          height\n        }\n        prefectures {\n          code\n          nameEn\n          nameJa\n          region\n        }\n      }\n      pageInfo {\n        page\n        pageSize\n        pageCount\n        total\n      }\n    }\n  }\n": typeof types.StagesDocument,
    "\n  query Stage($slug: String!, $locale: I18NLocaleCode) {\n    stages(filters: { slug: { eq: $slug } }, locale: $locale) {\n      documentId\n      slug\n      stageNumber\n      date\n      title\n      excerpt\n      body\n      startNameEn\n      endNameEn\n      startNameJa\n      endNameJa\n      routeFile\n      routePreview\n      gpxFile {\n        url\n      }\n      stats {\n        distanceKm\n        elevationGainM\n        elevationLossM\n        movingTimeMin\n        weather\n        tempC\n        sleptAt\n      }\n      coverImage {\n        url\n        alternativeText\n        width\n        height\n      }\n      gallery {\n        caption\n        alt\n        image {\n          url\n          alternativeText\n          width\n          height\n        }\n      }\n      prefectures {\n        code\n        nameEn\n        nameJa\n        region\n      }\n      seo {\n        metaTitle\n        metaDescription\n        ogImage {\n          url\n          width\n          height\n        }\n      }\n    }\n  }\n": typeof types.StageDocument,
    "\n  query RideTotals {\n    stages(pagination: { limit: 100 }) {\n      stats {\n        distanceKm\n        elevationGainM\n      }\n      prefectures {\n        code\n        nameEn\n        nameJa\n      }\n    }\n  }\n": typeof types.RideTotalsDocument,
    "\n  query AdjacentStages($numbers: [Int], $locale: I18NLocaleCode) {\n    stages(filters: { stageNumber: { in: $numbers } }, locale: $locale) {\n      slug\n      stageNumber\n      title\n      startNameEn\n      startNameJa\n      endNameEn\n      endNameJa\n    }\n  }\n": typeof types.AdjacentStagesDocument,
    "\n  query MapStages($locale: I18NLocaleCode) {\n    stages(\n      locale: $locale\n      sort: [\"stageNumber:asc\"]\n      pagination: { limit: 100 }\n    ) {\n      documentId\n      slug\n      stageNumber\n      date\n      title\n      excerpt\n      startNameEn\n      endNameEn\n      startNameJa\n      endNameJa\n      stats {\n        distanceKm\n        elevationGainM\n      }\n      coverImage {\n        url\n        alternativeText\n        width\n        height\n      }\n      prefectures {\n        region\n      }\n    }\n  }\n": typeof types.MapStagesDocument,
};
const documents: Documents = {
    "\n  query Page($slug: String!, $locale: I18NLocaleCode) {\n    pages(filters: { slug: { eq: $slug } }, locale: $locale) {\n      title\n      sections {\n        __typename\n        ... on ComponentSectionsHero {\n          heading\n          introduction\n          subheading\n        }\n        ... on ComponentSectionsFeaturedStages {\n          heading\n        }\n        ... on ComponentSectionsExploreCta {\n          heading\n        }\n      }\n      seo {\n        metaDescription\n        metaTitle\n        ogImage {\n          alternativeText\n          url\n          caption\n        }\n      }\n    }\n  }\n": types.PageDocument,
    "\n  query Prefectures {\n    prefectures {\n      nameJa\n      nameEn\n      code\n      region\n    }\n  }\n": types.PrefecturesDocument,
    "\n  query Stages(\n    $locale: I18NLocaleCode\n    $sort: [String]\n    $page: Int\n    $pageSize: Int\n    $filters: StageFiltersInput\n  ) {\n    stages_connection(\n      locale: $locale\n      sort: $sort\n      pagination: { page: $page, pageSize: $pageSize }\n      filters: $filters\n    ) {\n      nodes {\n        documentId\n        slug\n        stageNumber\n        date\n        title\n        excerpt\n        startNameEn\n        endNameEn\n        startNameJa\n        endNameJa\n        featured\n        routePreview\n        stats {\n          distanceKm\n          elevationGainM\n          movingTimeMin\n        }\n        coverImage {\n          url\n          alternativeText\n          width\n          height\n        }\n        prefectures {\n          code\n          nameEn\n          nameJa\n          region\n        }\n      }\n      pageInfo {\n        page\n        pageSize\n        pageCount\n        total\n      }\n    }\n  }\n": types.StagesDocument,
    "\n  query Stage($slug: String!, $locale: I18NLocaleCode) {\n    stages(filters: { slug: { eq: $slug } }, locale: $locale) {\n      documentId\n      slug\n      stageNumber\n      date\n      title\n      excerpt\n      body\n      startNameEn\n      endNameEn\n      startNameJa\n      endNameJa\n      routeFile\n      routePreview\n      gpxFile {\n        url\n      }\n      stats {\n        distanceKm\n        elevationGainM\n        elevationLossM\n        movingTimeMin\n        weather\n        tempC\n        sleptAt\n      }\n      coverImage {\n        url\n        alternativeText\n        width\n        height\n      }\n      gallery {\n        caption\n        alt\n        image {\n          url\n          alternativeText\n          width\n          height\n        }\n      }\n      prefectures {\n        code\n        nameEn\n        nameJa\n        region\n      }\n      seo {\n        metaTitle\n        metaDescription\n        ogImage {\n          url\n          width\n          height\n        }\n      }\n    }\n  }\n": types.StageDocument,
    "\n  query RideTotals {\n    stages(pagination: { limit: 100 }) {\n      stats {\n        distanceKm\n        elevationGainM\n      }\n      prefectures {\n        code\n        nameEn\n        nameJa\n      }\n    }\n  }\n": types.RideTotalsDocument,
    "\n  query AdjacentStages($numbers: [Int], $locale: I18NLocaleCode) {\n    stages(filters: { stageNumber: { in: $numbers } }, locale: $locale) {\n      slug\n      stageNumber\n      title\n      startNameEn\n      startNameJa\n      endNameEn\n      endNameJa\n    }\n  }\n": types.AdjacentStagesDocument,
    "\n  query MapStages($locale: I18NLocaleCode) {\n    stages(\n      locale: $locale\n      sort: [\"stageNumber:asc\"]\n      pagination: { limit: 100 }\n    ) {\n      documentId\n      slug\n      stageNumber\n      date\n      title\n      excerpt\n      startNameEn\n      endNameEn\n      startNameJa\n      endNameJa\n      stats {\n        distanceKm\n        elevationGainM\n      }\n      coverImage {\n        url\n        alternativeText\n        width\n        height\n      }\n      prefectures {\n        region\n      }\n    }\n  }\n": types.MapStagesDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Page($slug: String!, $locale: I18NLocaleCode) {\n    pages(filters: { slug: { eq: $slug } }, locale: $locale) {\n      title\n      sections {\n        __typename\n        ... on ComponentSectionsHero {\n          heading\n          introduction\n          subheading\n        }\n        ... on ComponentSectionsFeaturedStages {\n          heading\n        }\n        ... on ComponentSectionsExploreCta {\n          heading\n        }\n      }\n      seo {\n        metaDescription\n        metaTitle\n        ogImage {\n          alternativeText\n          url\n          caption\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query Page($slug: String!, $locale: I18NLocaleCode) {\n    pages(filters: { slug: { eq: $slug } }, locale: $locale) {\n      title\n      sections {\n        __typename\n        ... on ComponentSectionsHero {\n          heading\n          introduction\n          subheading\n        }\n        ... on ComponentSectionsFeaturedStages {\n          heading\n        }\n        ... on ComponentSectionsExploreCta {\n          heading\n        }\n      }\n      seo {\n        metaDescription\n        metaTitle\n        ogImage {\n          alternativeText\n          url\n          caption\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Prefectures {\n    prefectures {\n      nameJa\n      nameEn\n      code\n      region\n    }\n  }\n"): (typeof documents)["\n  query Prefectures {\n    prefectures {\n      nameJa\n      nameEn\n      code\n      region\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Stages(\n    $locale: I18NLocaleCode\n    $sort: [String]\n    $page: Int\n    $pageSize: Int\n    $filters: StageFiltersInput\n  ) {\n    stages_connection(\n      locale: $locale\n      sort: $sort\n      pagination: { page: $page, pageSize: $pageSize }\n      filters: $filters\n    ) {\n      nodes {\n        documentId\n        slug\n        stageNumber\n        date\n        title\n        excerpt\n        startNameEn\n        endNameEn\n        startNameJa\n        endNameJa\n        featured\n        routePreview\n        stats {\n          distanceKm\n          elevationGainM\n          movingTimeMin\n        }\n        coverImage {\n          url\n          alternativeText\n          width\n          height\n        }\n        prefectures {\n          code\n          nameEn\n          nameJa\n          region\n        }\n      }\n      pageInfo {\n        page\n        pageSize\n        pageCount\n        total\n      }\n    }\n  }\n"): (typeof documents)["\n  query Stages(\n    $locale: I18NLocaleCode\n    $sort: [String]\n    $page: Int\n    $pageSize: Int\n    $filters: StageFiltersInput\n  ) {\n    stages_connection(\n      locale: $locale\n      sort: $sort\n      pagination: { page: $page, pageSize: $pageSize }\n      filters: $filters\n    ) {\n      nodes {\n        documentId\n        slug\n        stageNumber\n        date\n        title\n        excerpt\n        startNameEn\n        endNameEn\n        startNameJa\n        endNameJa\n        featured\n        routePreview\n        stats {\n          distanceKm\n          elevationGainM\n          movingTimeMin\n        }\n        coverImage {\n          url\n          alternativeText\n          width\n          height\n        }\n        prefectures {\n          code\n          nameEn\n          nameJa\n          region\n        }\n      }\n      pageInfo {\n        page\n        pageSize\n        pageCount\n        total\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Stage($slug: String!, $locale: I18NLocaleCode) {\n    stages(filters: { slug: { eq: $slug } }, locale: $locale) {\n      documentId\n      slug\n      stageNumber\n      date\n      title\n      excerpt\n      body\n      startNameEn\n      endNameEn\n      startNameJa\n      endNameJa\n      routeFile\n      routePreview\n      gpxFile {\n        url\n      }\n      stats {\n        distanceKm\n        elevationGainM\n        elevationLossM\n        movingTimeMin\n        weather\n        tempC\n        sleptAt\n      }\n      coverImage {\n        url\n        alternativeText\n        width\n        height\n      }\n      gallery {\n        caption\n        alt\n        image {\n          url\n          alternativeText\n          width\n          height\n        }\n      }\n      prefectures {\n        code\n        nameEn\n        nameJa\n        region\n      }\n      seo {\n        metaTitle\n        metaDescription\n        ogImage {\n          url\n          width\n          height\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query Stage($slug: String!, $locale: I18NLocaleCode) {\n    stages(filters: { slug: { eq: $slug } }, locale: $locale) {\n      documentId\n      slug\n      stageNumber\n      date\n      title\n      excerpt\n      body\n      startNameEn\n      endNameEn\n      startNameJa\n      endNameJa\n      routeFile\n      routePreview\n      gpxFile {\n        url\n      }\n      stats {\n        distanceKm\n        elevationGainM\n        elevationLossM\n        movingTimeMin\n        weather\n        tempC\n        sleptAt\n      }\n      coverImage {\n        url\n        alternativeText\n        width\n        height\n      }\n      gallery {\n        caption\n        alt\n        image {\n          url\n          alternativeText\n          width\n          height\n        }\n      }\n      prefectures {\n        code\n        nameEn\n        nameJa\n        region\n      }\n      seo {\n        metaTitle\n        metaDescription\n        ogImage {\n          url\n          width\n          height\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query RideTotals {\n    stages(pagination: { limit: 100 }) {\n      stats {\n        distanceKm\n        elevationGainM\n      }\n      prefectures {\n        code\n        nameEn\n        nameJa\n      }\n    }\n  }\n"): (typeof documents)["\n  query RideTotals {\n    stages(pagination: { limit: 100 }) {\n      stats {\n        distanceKm\n        elevationGainM\n      }\n      prefectures {\n        code\n        nameEn\n        nameJa\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query AdjacentStages($numbers: [Int], $locale: I18NLocaleCode) {\n    stages(filters: { stageNumber: { in: $numbers } }, locale: $locale) {\n      slug\n      stageNumber\n      title\n      startNameEn\n      startNameJa\n      endNameEn\n      endNameJa\n    }\n  }\n"): (typeof documents)["\n  query AdjacentStages($numbers: [Int], $locale: I18NLocaleCode) {\n    stages(filters: { stageNumber: { in: $numbers } }, locale: $locale) {\n      slug\n      stageNumber\n      title\n      startNameEn\n      startNameJa\n      endNameEn\n      endNameJa\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MapStages($locale: I18NLocaleCode) {\n    stages(\n      locale: $locale\n      sort: [\"stageNumber:asc\"]\n      pagination: { limit: 100 }\n    ) {\n      documentId\n      slug\n      stageNumber\n      date\n      title\n      excerpt\n      startNameEn\n      endNameEn\n      startNameJa\n      endNameJa\n      stats {\n        distanceKm\n        elevationGainM\n      }\n      coverImage {\n        url\n        alternativeText\n        width\n        height\n      }\n      prefectures {\n        region\n      }\n    }\n  }\n"): (typeof documents)["\n  query MapStages($locale: I18NLocaleCode) {\n    stages(\n      locale: $locale\n      sort: [\"stageNumber:asc\"]\n      pagination: { limit: 100 }\n    ) {\n      documentId\n      slug\n      stageNumber\n      date\n      title\n      excerpt\n      startNameEn\n      endNameEn\n      startNameJa\n      endNameJa\n      stats {\n        distanceKm\n        elevationGainM\n      }\n      coverImage {\n        url\n        alternativeText\n        width\n        height\n      }\n      prefectures {\n        region\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;